//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Note
{
    public int Id { get; set; }
    public string NoteHead { get; set; }
    public string NoteDate { get; set; }
    public string NoteText { get; set; }
    public int UserId { get; set; }
    public string NoteColor { get; set; }
}

public partial class Task
{
    public int Id { get; set; }
    public string TaskText { get; set; }
    public string TaskDate { get; set; }
    public int NoteId { get; set; }
}

public partial class User
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string Email { get; set; }
    public string Password { get; set; }
}
